name: moolwmsstore
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2   
  dio: ^5.4.1
  get: ^4.6.6
  shared_preferences:
  gap:
  cached_network_image: ^3.3.1
  dropdown_button2: ^2.3.9
  freezed_annotation: ^2.4.1
  image_picker: ^1.1.1
  get_it: ^7.6.7
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  otp_text_field_v2: ^1.0.3
  dotted_border: ^2.1.0
  intl:
  flutter_spinkit:
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  hive_flutter:
  path_provider:
  restart_app: ^1.2.1
  msh_checkbox: ^2.0.1
  zoom_widget: ^2.0.1
  file_picker: ^8.0.3
  qr_bar_code_scanner_dialog: ^0.0.5
  throttling: ^2.0.1
  number_text_input_formatter: ^1.0.0+8
  camera: ^0.11.0
  hexcolor: ^3.0.1
  gif_view: ^0.4.3
  omni_datetime_picker: ^1.1.0
  pinch_zoom: ^2.0.0
  pretty_qr_code: ^3.3.0
  infinite_scroll_pagination: ^4.0.0
  loading_animation_widget: ^1.2.1
  qr_flutter: ^4.1.0
  widgets_to_image: ^1.0.0
  share_plus: ^9.0.0
  liquid_pull_to_refresh: ^3.0.1
  blur: ^4.0.0
  elapsed_time_display: ^1.0.0
  calendar_view: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # auto_route_generator: ^8.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter_launcher_icons:
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/appLogo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

# flutter_native_splash:
#   color: "#FFFFFF"
#   image: assets/Layer_5.png
#   android: true
#   ios: true
#   web: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/languages/
    - assets/images/
    # - assets/3d/
    - assets/gifs/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/font/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/font/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/font/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/font/SF-Pro-Display-Black.otf
          weight: 900
